import type { NextPage } from "next";
import Head from "next/head";
import CountryCard from "../components/CountryCard";
import { GetServerSideProps } from "next";
import Search from "../components/Search";
import { useEffect, useState } from "react";
import FilterByRegion from "../components/FilterByRegion";
import Card from "../components/shared/Card";

const Home: NextPage = ({ data, randomNumber }) => {
  const [showCountries, setShowCountries] = useState([]);
  const [search, setSearch] = useState("");
  const [filterByRegionMenu, setFilterByRegionMenu] = useState(false);

  useEffect(() => {
    const first8 = data.slice(randomNumber, randomNumber + 8);
    if (search)
      setShowCountries(
        data
          .filter((country) =>
            country.name.common.toLowerCase().includes(search.toLowerCase())
          )
          .slice(0, 8)
      );
    else setShowCountries(first8);
  }, [search]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dark:bg-[#202C37] bg-[#FAFAFA] min-h-screen max-w-screen">
        <div className="md:px-14 sm:px-9 px-4 lg:px-24 flex sm:justify-between sm:items-center py-9 relative flex-col sm:flex-row justify-center items-start">
          <Search search={search} setSearch={setSearch} />
          <FilterByRegion
            className="mt-7 sm:mt-0"
            onClick={() => setFilterByRegionMenu(true)}
            onMouseEnter={() => setFilterByRegionMenu(true)}
          />
          {filterByRegionMenu && (
            <Card
              className="absolute  lg:right-[6rem] md:right-[3.5rem] sm:right-[2.3rem]  w-52 top-[11.5rem] sm:top-[6rem] z-50 border-none  py-4 flex flex-col justify-center items-start"
              onMouseLeave={() => {
                setTimeout(() => {
                  setFilterByRegionMenu(false);
                }, 300);
              }}
            >
              <ul className="w-full">
                <li
                  className="px-6 py-1 dark:hover:bg-white hover:bg-opacity-[0.02] dark:hover:bg-opacity-10 hover:bg-black cursor-pointer"
                  onClick={() => {
                    setShowCountries(
                      data
                        .filter(
                          (country) => country.region.toLowerCase() === "africa"
                        )
                        .slice(0, 8)
                    );
                    setFilterByRegionMenu(false);
                  }}
                >
                  Africa
                </li>
                <li
                  className="px-6 py-1 dark:hover:bg-white hover:bg-opacity-[0.02] dark:hover:bg-opacity-10 hover:bg-black cursor-pointer"
                  onClick={() => {
                    setShowCountries(
                      data
                        .filter(
                          (country) =>
                            country.region.toLowerCase() === "america"
                        )
                        .slice(0, 8)
                    );
                    setFilterByRegionMenu(false);
                  }}
                >
                  America
                </li>
                <li
                  className="px-6 py-1 dark:hover:bg-white hover:bg-opacity-[0.02] dark:hover:bg-opacity-10 hover:bg-black cursor-pointer"
                  onClick={() => {
                    setShowCountries(
                      data
                        .filter(
                          (country) => country.region.toLowerCase() === "asia"
                        )
                        .slice(0, 8)
                    );
                    setFilterByRegionMenu(false);
                  }}
                >
                  Asia
                </li>
                <li
                  className="px-6 py-1 dark:hover:bg-white hover:bg-opacity-[0.02] dark:hover:bg-opacity-10 hover:bg-black cursor-pointer"
                  onClick={() => {
                    setShowCountries(
                      data
                        .filter(
                          (country) => country.region.toLowerCase() === "europe"
                        )
                        .slice(0, 8)
                    );
                    setFilterByRegionMenu(false);
                  }}
                >
                  Europe
                </li>
                <li
                  className="px-6 py-1 dark:hover:bg-white hover:bg-opacity-[0.02] dark:hover:bg-opacity-10 hover:bg-black cursor-pointer"
                  onClick={() => {
                    setShowCountries(
                      data
                        .filter(
                          (country) =>
                            country.region.toLowerCase() === "oceania"
                        )
                        .slice(0, 8)
                    );
                    setFilterByRegionMenu(false);
                  }}
                >
                  Oceania
                </li>
              </ul>
            </Card>
          )}
        </div>
        <div className="w-full flex justify-center sm:justify-between items-center flex-wrap md:px-14 sm:px-9 px-4 lg:px-24 ">
          {showCountries.map((country) => (
            <div className="pr-3 py-4" key={country.name.official}>
              <CountryCard
                name={country.name.common}
                capital={country.capital[0]}
                population={+country.population}
                flag={country.flags.png}
                region={country.region}
              />
            </div>
          ))}
        </div>
      </div>
    </>
  );
};
export const getServerSideProps: GetServerSideProps = async () => {
  const data = await (
    await fetch(
      "https://restcountries.com/v3.1/all?fields=name,capital,population,flags,region"
    )
  ).json();
  const randomNumber = Math.floor(Math.random() * 241);

  return {
    props: { data, randomNumber }, // will be passed to the page component as props
  };
};

export default Home;
